<?php
$db_host = "localhost";
$db_user = "root";
$db_password = "";
$db_name = "donation";

$name = $_POST['firstname'];
$email = $_POST['email'];
$address = $_POST['address'];
$city = $_POST['city'];
$number = $_POST['number'];
$amount = $_POST['amount'];


// Create Connection
//$q = intval($_GET['q']);

$conn = new mysqli($db_host, $db_user, $db_password, $db_name);

// Check Connection
if($conn->connect_error) {
 die("connection failed");
}
else{
    $stmt = $conn->prepare("insert into donation(name,email,address,city,number,amount)values(?,?,?,?,?,?)");
    $stmt->bind_param("sssssi",$name,$email,$address,$city,$number,$amount);
    $stmt->execute();
    echo 'success';
    $stmt->close();
    $conn->close();
}
?>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_2WYNlJmQNTvtIL" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount=<?php echo $amount * 100 ?> // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="donation mfs"
    data-name="MGM Donations"
    data-description="lets help rock on"
    data-image="http://i1.wp.com/ytimg.googleusercontent.com/vi/e-b_Rc-OdCA/mqdefault.jpg"

    data-prefill.contact="<?php echo $_POST['number'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-theme.color="#F37254"
></script>

<input type="hidden" custom="Hidden Element" name="hidden">
</form>





